#ifndef H_USPACE_DIRECTORY
#define H_USPACE_DIRECTORY
#define DIRECTORY_QUERYNODE			0x14
#define DIRECTORY_CREATENODE		0x15
#define DIRECTORY_QUERYDIR			0x16

#define DIRECTORY_IF_VCONSOLE		0x1000

#endif